### ISSUE TITLE
Errors when running the tutorial notebook

### ISSUE THREAD

**Issue by Jiacheng06** [pikulsomesh/tutorials#1]
Hi,

When I ran the third cell of the given tutorial notebook Tutorial_CPP.ipynb, there would be an error "/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/local/lib/python3.7/site-packages/rdkit/DataStructs/cDataStructs.so)". Do you know how to solve this problem? I have tried several ways but all failed.

Thanks a lot,
Jiacheng

**Comment by pikulsomesh** [comment]
Hi 
This is a gcc problem, where you have to update the GCC library. Follow the steps [here](https://stackoverflow.com/questions/63190229/glibcxx-3-4-26-not-found-running-cross-complied-program-on-beaglebone).
SM
